// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdiTuxO8bK8TLR_UZIf8EWVtaZz_y2HSw',
    appId: '1:820223383080:web:39c54b7eb7f0ef164c471d',
    messagingSenderId: '820223383080',
    projectId: 'notes-flutt-project',
    authDomain: 'notes-flutt-project.firebaseapp.com',
    storageBucket: 'notes-flutt-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTzIEMj2-AQaWI-mFJEMCedo0d48_AFRY',
    appId: '1:820223383080:android:ccf09b2ddcab3bdb4c471d',
    messagingSenderId: '820223383080',
    projectId: 'notes-flutt-project',
    storageBucket: 'notes-flutt-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDRwKmGlJOsss6b9hKrjmTpx5jJ2oFSrE',
    appId: '1:820223383080:ios:19f7512aa00f556f4c471d',
    messagingSenderId: '820223383080',
    projectId: 'notes-flutt-project',
    storageBucket: 'notes-flutt-project.appspot.com',
    iosClientId: '820223383080-jqraai55u659bre59otigu9ij89cliai.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCourseForBeginners',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDRwKmGlJOsss6b9hKrjmTpx5jJ2oFSrE',
    appId: '1:820223383080:ios:19f7512aa00f556f4c471d',
    messagingSenderId: '820223383080',
    projectId: 'notes-flutt-project',
    storageBucket: 'notes-flutt-project.appspot.com',
    iosClientId: '820223383080-jqraai55u659bre59otigu9ij89cliai.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCourseForBeginners',
  );
}
